# Generated by Django 5.2.3 on 2025-06-12 23:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                ("linkedin_url", models.URLField(blank=True, verbose_name="LinkedIn")),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Местоположение"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Кандидат",
                "verbose_name_plural": "Кандидаты",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название компании"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("website", models.URLField(blank=True, verbose_name="Веб-сайт")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Компания",
                "verbose_name_plural": "Компании",
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название вакансии"),
                ),
                ("description", models.TextField(verbose_name="Описание вакансии")),
                ("requirements", models.TextField(verbose_name="Требования")),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("junior", "Junior (0-2 года)"),
                            ("middle", "Middle (2-5 лет)"),
                            ("senior", "Senior (5+ лет)"),
                        ],
                        max_length=20,
                        verbose_name="Уровень опыта",
                    ),
                ),
                (
                    "salary_min",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Зарплата от"
                    ),
                ),
                (
                    "salary_max",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Зарплата до"
                    ),
                ),
                ("location", models.CharField(max_length=200, verbose_name="Локация")),
                (
                    "remote_work",
                    models.BooleanField(default=False, verbose_name="Удаленная работа"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активная"),
                            ("paused", "Приостановлена"),
                            ("closed", "Закрыта"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requirements_embedding",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Embedding требований"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.company",
                        verbose_name="Компания",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создано пользователем",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вакансия",
                "verbose_name_plural": "Вакансии",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cover_letter",
                    models.TextField(
                        blank=True, verbose_name="Сопроводительное письмо"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает обработки"),
                            ("processing", "Обрабатывается"),
                            ("approved", "Одобрено"),
                            ("rejected", "Отклонено"),
                            ("interviewed", "Прошел собеседование"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "ai_score",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="AI оценка",
                    ),
                ),
                ("ai_feedback", models.TextField(blank=True, verbose_name="AI отзыв")),
                ("hr_notes", models.TextField(blank=True, verbose_name="Заметки HR")),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.candidate",
                        verbose_name="Кандидат",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.job",
                        verbose_name="Вакансия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
                "ordering": ["-applied_at"],
                "unique_together": {("candidate", "job")},
            },
        ),
    ]
