# Generated by Django 5.2.3 on 2025-06-13 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="hr_notes",
        ),
        migrations.AddField(
            model_name="application",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Заметки HR"),
        ),
    ]
