# Generated by Django 5.2.3 on 2025-06-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_candidate_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="views_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество просмотров"
            ),
        ),
    ]
