# Generated by Django 5.2.3 on 2026-06-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_company_options_company_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Полная занятость'), ('part_time', 'Частичная занятость'), ('internship', 'Стажировка'), ('project', 'Проектная работа'), ('remote', 'Удалённо')], default='full_time', max_length=20, verbose_name='Тип занятости'),
        ),
        migrations.AddField(
            model_name='job',
            name='skills_required',
            field=models.JSONField(blank=True, default=list, help_text="Список строк, например: ['Python', 'Django']", verbose_name='Ключевые навыки (теги)'),
        ),
    ]
