# Generated by Django 5.2.3 on 2026-06-26 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_job_employment_type_job_skills_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=300, verbose_name='Учебное заведение')),
                ('degree', models.CharField(choices=[('secondary', 'Среднее'), ('vocational', 'Среднее профессиональное'), ('bachelor', 'Бакалавр'), ('master', 'Магистр'), ('phd', 'Кандидат/Доктор наук'), ('courses', 'Курсы'), ('certification', 'Сертификация')], default='bachelor', max_length=30, verbose_name='Степень')),
                ('field_of_study', models.CharField(blank=True, max_length=200, verbose_name='Специальность')),
                ('start_year', models.PositiveIntegerField(verbose_name='Год начала')),
                ('end_year', models.PositiveIntegerField(verbose_name='Год окончания')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='core.candidate', verbose_name='Кандидат')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образование',
                'ordering': ['-end_year'],
                'indexes': [models.Index(fields=['candidate', '-end_year'], name='core_educat_candida_e2bd0f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Навык')),
                ('level', models.CharField(choices=[('beginner', 'Начальный'), ('intermediate', 'Средний'), ('expert', 'Продвинутый')], default='intermediate', max_length=20, verbose_name='Уровень')),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True, verbose_name='Опыт (лет)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.candidate', verbose_name='Кандидат')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['candidate', 'name'], name='core_skill_candida_3e9ae4_idx')],
                'unique_together': {('candidate', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, verbose_name='Компания')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, help_text='Оставьте пустым, если работаете здесь сейчас', null=True, verbose_name='Дата окончания')),
                ('is_current', models.BooleanField(default=False, verbose_name='Текущее место работы')),
                ('description', models.TextField(blank=True, verbose_name='Обязанности и достижения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='core.candidate', verbose_name='Кандидат')),
            ],
            options={
                'verbose_name': 'Опыт работы',
                'verbose_name_plural': 'Опыт работы',
                'ordering': ['-is_current', '-start_date'],
                'indexes': [models.Index(fields=['candidate', '-start_date'], name='core_workex_candida_d7b808_idx')],
            },
        ),
    ]
