# Generated by Django 5.2.3 on 2025-06-13 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=60, verbose_name="Длительность (мин)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Тип собеседования",
                "verbose_name_plural": "Типы собеседований",
            },
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_at", models.DateTimeField(verbose_name="Запланировано на")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=60, verbose_name="Длительность (мин)"
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("online", "Онлайн"),
                            ("offline", "Офлайн"),
                            ("phone", "Телефон"),
                        ],
                        max_length=20,
                        verbose_name="Формат",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Место/Ссылка"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Запланировано"),
                            ("confirmed", "Подтверждено"),
                            ("in_progress", "В процессе"),
                            ("completed", "Завершено"),
                            ("cancelled", "Отменено"),
                            ("no_show", "Не явился"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Заметки")),
                (
                    "preparation_notes",
                    models.TextField(blank=True, verbose_name="Заметки для подготовки"),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, verbose_name="Обратная связь"),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        null=True,
                        verbose_name="Оценка (1-5)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.application",
                        verbose_name="Заявка",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.candidate",
                        verbose_name="Кандидат",
                    ),
                ),
                (
                    "interviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Интервьюер",
                    ),
                ),
                (
                    "interview_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calendar_app.interviewtype",
                        verbose_name="Тип собеседования",
                    ),
                ),
            ],
            options={
                "verbose_name": "Собеседование",
                "verbose_name_plural": "Собеседования",
                "ordering": ["scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="InterviewAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Понедельник"),
                            (1, "Вторник"),
                            (2, "Среда"),
                            (3, "Четверг"),
                            (4, "Пятница"),
                            (5, "Суббота"),
                            (6, "Воскресенье"),
                        ],
                        verbose_name="День недели",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Время начала")),
                ("end_time", models.TimeField(verbose_name="Время окончания")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "interviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Интервьюер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Доступность для собеседований",
                "verbose_name_plural": "Доступности для собеседований",
                "unique_together": {
                    ("interviewer", "weekday", "start_time", "end_time")
                },
            },
        ),
        migrations.CreateModel(
            name="InterviewTimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                ("start_time", models.TimeField(verbose_name="Время начала")),
                ("end_time", models.TimeField(verbose_name="Время окончания")),
                (
                    "is_booked",
                    models.BooleanField(default=False, verbose_name="Забронировано"),
                ),
                (
                    "interview",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calendar_app.interview",
                        verbose_name="Собеседование",
                    ),
                ),
                (
                    "interviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Интервьюер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Временной слот",
                "verbose_name_plural": "Временные слоты",
                "ordering": ["date", "start_time"],
                "unique_together": {("interviewer", "date", "start_time")},
            },
        ),
    ]
