# Generated by Django 5.2.3 on 2025-06-12 23:17

import django.core.validators
import django.db.models.deletion
import resume.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=resume.models.resume_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "docx"]
                            )
                        ],
                        verbose_name="Файл резюме",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        max_length=255, verbose_name="Оригинальное имя файла"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(verbose_name="Размер файла (байты)"),
                ),
                (
                    "extracted_text",
                    models.TextField(blank=True, verbose_name="Извлеченный текст"),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("ru", "Русский"),
                            ("en", "English"),
                            ("auto", "Автоопределение"),
                        ],
                        default="auto",
                        max_length=10,
                        verbose_name="Язык",
                    ),
                ),
                ("skills", models.JSONField(default=list, verbose_name="Навыки")),
                (
                    "experience_years",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Опыт (лет)"
                    ),
                ),
                (
                    "education",
                    models.JSONField(default=list, verbose_name="Образование"),
                ),
                (
                    "work_experience",
                    models.JSONField(default=list, verbose_name="Опыт работы"),
                ),
                (
                    "text_embedding",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Text Embedding"
                    ),
                ),
                (
                    "skills_embedding",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Skills Embedding"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Загружено"),
                            ("processing", "Обрабатывается"),
                            ("processed", "Обработано"),
                            ("error", "Ошибка"),
                        ],
                        default="uploaded",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "processing_error",
                    models.TextField(blank=True, verbose_name="Ошибка обработки"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.application",
                        verbose_name="Заявка",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.candidate",
                        verbose_name="Кандидат",
                    ),
                ),
            ],
            options={
                "verbose_name": "Резюме",
                "verbose_name_plural": "Резюме",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ResumeAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key_skills",
                    models.JSONField(default=list, verbose_name="Ключевые навыки"),
                ),
                (
                    "experience_summary",
                    models.TextField(blank=True, verbose_name="Краткое описание опыта"),
                ),
                (
                    "education_level",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Уровень образования"
                    ),
                ),
                (
                    "completeness_score",
                    models.FloatField(default=0.0, verbose_name="Полнота резюме"),
                ),
                (
                    "relevance_keywords",
                    models.JSONField(
                        default=list, verbose_name="Релевантные ключевые слова"
                    ),
                ),
                ("analyzed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resume",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resume.resume",
                        verbose_name="Резюме",
                    ),
                ),
            ],
            options={
                "verbose_name": "Анализ резюме",
                "verbose_name_plural": "Анализы резюме",
            },
        ),
    ]
