# Generated by Django 5.2.3 on 2025-06-13 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Код"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "email_subject_template",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Шаблон темы email"
                    ),
                ),
                (
                    "email_body_template",
                    models.TextField(blank=True, verbose_name="Шаблон тела email"),
                ),
                (
                    "sms_template",
                    models.TextField(blank=True, verbose_name="Шаблон SMS"),
                ),
            ],
            options={
                "verbose_name": "Тип уведомления",
                "verbose_name_plural": "Типы уведомлений",
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_enabled",
                    models.BooleanField(default=True, verbose_name="Email уведомления"),
                ),
                (
                    "sms_enabled",
                    models.BooleanField(default=False, verbose_name="SMS уведомления"),
                ),
                (
                    "in_app_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Уведомления в приложении"
                    ),
                ),
                (
                    "new_application_email",
                    models.BooleanField(
                        default=True, verbose_name="Новая заявка (Email)"
                    ),
                ),
                (
                    "interview_reminder_email",
                    models.BooleanField(
                        default=True, verbose_name="Напоминание о собеседовании (Email)"
                    ),
                ),
                (
                    "interview_reminder_sms",
                    models.BooleanField(
                        default=False, verbose_name="Напоминание о собеседовании (SMS)"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки уведомлений",
                "verbose_name_plural": "Настройки уведомлений",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email получателя"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Телефон получателя"
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("in_app", "В приложении"),
                            ("push", "Push уведомление"),
                        ],
                        max_length=20,
                        verbose_name="Канал",
                    ),
                ),
                (
                    "subject",
                    models.CharField(blank=True, max_length=200, verbose_name="Тема"),
                ),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает отправки"),
                            ("sent", "Отправлено"),
                            ("delivered", "Доставлено"),
                            ("failed", "Ошибка"),
                            ("cancelled", "Отменено"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Запланировано на"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Отправлено в"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Доставлено в"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Сообщение об ошибке"),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество повторов"
                    ),
                ),
                (
                    "max_retries",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Максимум повторов"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.candidate",
                        verbose_name="Кандидат",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "notification_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notifications.notificationtype",
                        verbose_name="Тип уведомления",
                    ),
                ),
            ],
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("ru", "Русский"), ("en", "English")],
                        default="ru",
                        max_length=10,
                        verbose_name="Язык",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("in_app", "В приложении"),
                            ("push", "Push уведомление"),
                        ],
                        max_length=20,
                        verbose_name="Канал",
                    ),
                ),
                (
                    "subject_template",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Шаблон темы"
                    ),
                ),
                ("body_template", models.TextField(verbose_name="Шаблон сообщения")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notification_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notifications.notificationtype",
                        verbose_name="Тип уведомления",
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаблон уведомления",
                "verbose_name_plural": "Шаблоны уведомлений",
                "unique_together": {("notification_type", "language", "channel")},
            },
        ),
    ]
